# Generated by Django 3.1.1 on 2020-10-06 20:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('entry_text', models.TextField()),
                ('slug', models.CharField(max_length=40, unique=True)),
                ('pub_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
