# Generated by Django 3.1.1 on 2020-10-08 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='slug',
            field=models.CharField(editable=False, max_length=40, unique=True),
        ),
    ]
